# .air.toml
root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/glow ."
bin = "tmp/glow serve"
full_bin = "./tmp/glow serve"
include_ext = ["go", "tpl", "tmpl", "html"]
exclude_dir = ["assets", "tmp"]
include_dir = ["."]
exclude_file = []
delay = 1000
stop_on_error = true
send_interrupt = false
delay_interrupt = 500

[log]
time = false

[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
clean_on_exit = true
