version: '3.8'

services:
  glow-api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: glow-api
    command: ['air', '-c', '.air.toml']
    restart: unless-stopped
    env_file:
      - .env.development
    ports:
      - '8081:8081'
    environment:
      - GO_ENV=development
      - DB_PORT=5432
      - DB_HOST=glow_postgres
      - DB_NAME=glow_db
      - DB_USER=glow_db
      - DB_PASS=glow_dev_password
      - DB_SSLMODE=disable
      - DB_TIMEZONE=Asia/Jakarta
      - MIGRATION_PATH=infra/databases/migrations
      - MIGRATE_ENABLED=true
      - JWT_SECRET=glow_jwt_secret
      - REDIS_URL=redis://glow_redis:6379
      - RABBITMQ_URL=amqp://guest:guest@glow-rabbitmq:5672
    volumes:
      - .:/app
    depends_on:
      - glow_postgres
      - glow_redis
      - glow-rabbitmq
    networks:
      - glow_network

  glow_postgres:
    image: postgres:15-alpine
    container_name: glow_postgres
    restart: always
    environment:
      POSTGRES_USER: glow_db
      POSTGRES_PASSWORD: glow_dev_password
      POSTGRES_DB: glow_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - glow_network

  glow_redis:
    image: redis:alpine
    container_name: glow_redis
    restart: always
    ports:
      - '6379:6379'
    networks:
      - glow_network
    volumes:
      - redis_data:/data

  glow-rabbitmq:
    image: rabbitmq:3-management
    container_name: glow-rabbitmq
    restart: always
    ports:
      - '5672:5672'
      - '15672:15672'
    networks:
      - glow_network
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/mnesia

networks:
  glow_network:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
  rabbitmq_data:
